#!/bin/bash

PROJECT_ROOT=$HOME/.amionline
HEARTBEAT_LOGS=heartbeats.log
DATETIME=$(date +%D-%T-%s)

IDLE_THRESHOLD=30
IDLE_SEC=$(ioreg -c IOHIDSystem \
    | grep -oE 'HIDIdleTime.*[0-9]+' \
    | awk '{ print int($NF/1000000000) }')

# TODO: modify actions to hit user status endpoints
# once relevant api has been created and deployed
if [ "$IDLE_SEC" -ge "$IDLE_THRESHOLD" ]; then 
    echo "[$USER] $DATETIME ... inactive" \
        >> $PROJECT_ROOT/$HEARTBEAT_LOGS
else
    echo "[$USER] $DATETIME ... active" \
        >> $PROJECT_ROOT/$HEARTBEAT_LOGS
fi
